all:
	iverilog -o testbench Adder.v ALU.v ALU_Control.v AND.v Control.v CPU.v Data_Memory.v Equal.v EX_MEM.v Flush_MUX.v Forward_Unit.v ForwardMUX.v Hazard_Detection_Unit.v ID_EX.v IF_ID.v Instruction_Memory.v MEM_WB.v MUX32.v MUX5.v PC.v Registers.v Shift_Left2.v Shift_Left2_Concat.v Signed_Extend.v testbench.v

run:  ./testbench
